client:
  url: http://api:8080

service:
  api:
    name: api-service
    http:
      port: 8080
  worker:
    name: worker-service
  projection:
    name: projection-service
  callback:
    name: callback-service
    http:
      port: 8081

psp:
  url: http://mockpsp:8082
  callback_url: http://callback:8081/webhooks/psp

postgres:
  url: postgres://admin:admin@postgres:5432/payments?sslmode=disable
  pool:
    max_conns: 16
    min_conns: 1
    max_conn_lifetime: 1h

kafka:
  brokers:
    - kafka:9092
  topics:
    commands: payments.commands
    events:   payments.events
  group_ids:
    worker: payment-worker
    projection: payment-projection 

observability:
  otlp:
    endpoint: jaeger:4318
